trigger:
  branches:
    include: ['*']

jobs:
 - job:
   displayName: "Build & Test"
   strategy:
     matrix:
       Stable:
         toolchain: stable
       Beta:
         toolchain: beta
       Nightly:
         toolchain: nightly
   pool:
     vmImage: ubuntu-latest
   steps:
    - template: ci/install-rust.yml
      parameters:
        toolchain: $(toolchain)
    - script: rustup component add clippy
      displayName: "Add Clippy"
    - bash: cargo test
      displayName: "Build & Test"
    - bash: cargo test --features alloc
      displayName: "Build & Test Alloc"
    - bash: cargo clippy -- -D warnings
