[package]
name = "tinydeque_benchmarks"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
getrandom = "0.2.0"
tinydeque = { path = "../", features = ["alloc"] }
